### PR TITLE
Added development specific problems that we should try to solve as part of this redesign

### PR DESCRIPTION
**Pull request by pawelpabich**
@NickJosevski can you see any other major sources of bugs in permission related code?

### CODE REVIEW

**Comment by NickJosevski** [comment]
@pawelpabich indeed, I'll take your branch/PR and add a bit more.

**Comment by pawelpabich** [comment]
thanks

**Comment by NickJosevski** [comment]
oops my IDE removed trailing white space, so I "touched" more lines than I intended.

**Comment by michaelnoonan** [comment]
Some good thoughts in here @NickJosevski. I like the idea that we can address all of the developer concerns with as much importance as the customer concerns. If we make the development experience easier, and less error prone, we'll inevitably get less bugs and technical debt from this area.

**Comment by pawelpabich** [comment]
@MJRichardson is this one going to be merged/closed?

**Pull request merged**
